---
spring:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:C:/Users/SEBIN/Desktop/programming/fall2020/cs321serverside/homework/neiu-cs-321/DoodleBoard/dboarddata
    username: admin
    password:
    driver-class-name: org.h2.Driver

doodlefeed:
  posts:
    feedSize: 5

server:
  error:
    whitelabel:
      enabled: false
    path: /error
